### ISSUE TITLE
Halls Bug to fix

### ISSUE THREAD

**Issue by WojciechPotoniec** [StefanoDaniello/Bollywood#1]
Buongiorno per favore puoi verificare tutte le funzionalità connesse alla rotta delle sale?
Ho bisogno che mi verifichi tutti i possibili errori che possono generarsi nelle CRUD.
appena fatto un check complessivo vorrei avere un rapporto preciso di tutti gli errori e dei fix eseguiti.
Aprite un branch e lavorate sul vostro ramo poi eseguiremo un merge di tutto.

Buona giornata e buon lavoro ricordo che la scadenza è prevista per il 18/06/2024.

**Comment by lorenzo-de-giorgi** [comment]
git fetch origin
git checkout 1-halls-bug-to-fix
